projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/api/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api/API.ts
        docsFilePath: src/api/graphql
        region: us-east-1
        apiId: nfxro7s4pzezpavtr3vwjqy7jq
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
